#!/bin/bash 
set -e
main="main.cpp"
dir=""

function new() {
  echo "unimplemented"
}

function run(){
  action=$1
}

function print_help(){
  echo "Usage of $0"
  echo "Argumento no válido. Los posibles valores son: cpp, java, php o vue."
}

if [[ "$#" -eq 0 ]]; then
  print_help
  exit 1
fi

# n => new
# r => run
# u => undone
# t => type

shortopts="n:r:u:t:"
opts=$( getopt -o "$shortopts" -l "help:" -n "${0##*/}" -- "$@" )

eval "set -- $opts"

name=''

new=0
reset=0
undone=0
typ=""

while (( $# >> 0 )); do
  case "$1" in
    ("-n")
      name=$2; new=1 ;shift 2
      ;;
    ("-r")
      name=$2; reset=1; shift 2
      ;;
    ("-u")
      name=$2; undone=1; shift 2
      ;;
    ("-t")
      typ=$2; shift 2
      ;;
    ("--help")
      print_help
      shift 1
      break
      ;;
    ("--")
      shift 1
      break
      ;;
  esac
done

if [[ $new -eq 1 && -z $name ]]; then
  exit 2
fi

if [ -z $typ ]; then
  typ=$1
fi

case "$typ" in
  cpp)
    dir=cpp_projects
    ;;
  java)
    dir=java_projects
    ;;
  php)
    dir=php_projects
    ;;
  vue)
    dir=web_projects
    ;;
  *)
    echo "Argumento no válido. Los posibles valores son: cpp, java, php o vue."
    exit 3
    ;;
esac

uri="$HOME/git/${dir}" 

if [[ $new -eq 1 ]]; then
  dir="${uri}/${name}"

  if [ -d $dir ]; then
    echo "El proyecto ya existe."
    exit 4
  fi

  cmd=''
  builder=0

  case "$typ" in
    cpp)
      cmd="touch ${main}"
      ;;
    java)
      cmd=""
      ;;
    php)
      cmd="touch index.php"
      ;;
    vue)
      cmd="vue create --preset projects -b ${name}"
      builder=1
      ;;
  esac

  if [ $builder -eq 0 ]; then
    mkdir $dir
    cd $dir
    eval $cmd
  else
    cd $uri
    eval $cmd
    cd $name
  fi
else
  dirs=`ls $uri`

  i=1

  if [ $# -eq 2 ]; then
    num=$2
  else
    for dir in $dirs; do
      if [ -d "$uri/$dir" ]; then
        echo "$i- $dir"
        ((i++))
      fi
    done
    read -p ">> " num
  fi

  if [ $num -eq 0 ]; then
    exit 0
  fi

  dir=$(echo "$dirs" | sed "${num}q;d")
  dir=$(echo "$dir" | sed 's/[0-9]\+- //')

  echo $dir
  cd $uri/$dir
fi

if [[ -f .nvim ]]; then
  nvim -S .nvim
else
  nvim .
fi
